parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     3306
    database_name:     totalplanning
    database_user:     root
    database_password: 

    mailer_transport: smtp
    mailer_encryption: ssl
    mailer_port: 143
    mailer_host: smtpout.secureserver.net
    mailer_user: tmp@ivqmobile.com
    mailer_password: tmp123
    secret: TOken23A_d236142xcvxFFsc
    locale:            es
