parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     3306
    database_name:     prueba
    database_user:     root
    database_password: 

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            es
    secret:            khasKJ_Yuasda634lk__*****.3rfThas
