site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

general_config:
    resource: "@GeneralConfigBundle/Resources/config/routing.yml"
    prefix:   /dashboard/config

horario:
    resource: "@HorarioBundle/Resources/config/routing.yml"
    prefix:   /dashboard/horario
planeacion_admin:
    resource: "@PlaneacionAdminBundle/Resources/config/routing.yml"
    prefix:   /dashboard/planeacion

#
#arquitectura:
#    resource: "@ArquitecturaBundle/Resources/config/routing.yml"
#    prefix:   /arquitectura

security:
    resource: "@MySecurityBundle/Resources/config/routing.yml"
    prefix:   /dashboard/security

comun:
    resource: "@ComunBundle/Resources/config/routing.yml"
    prefix:   /dashboard
#
#biomexpress_services:
#    resource: "@BiomexpressServicesBundle/Controller/DefaultController.php"
#    type:     annotation
#    prefix:   /services


#menu:
#    resource: "@ADEPSOFTMenuBundle/Resources/config/routing.yml"
#    prefix:   /

#------------------FOSUser------------------
change_pass:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
fos_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile
fos_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /registration
#fos_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
fos_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
