jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
           # oauth:
            #    failure_path: your_path
             #   login_path: your_path
            #    check_path: /connect_check
            #    provider: fos_userbundle
            #      resource_owners:
            #          facebook: "/login/check-facebook"
            #          google: "/login/check-google"
            #      oauth_user_provider:
            #          service: app.provider.oauth
            form_login:
                use_referer : true
                default_target_path: home_page
                always_use_default_target_path: true
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
#        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/portada, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mail/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/open, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/planeacion/profesor/hoja, role: [ROLE_PROFESOR] }
        - { path: ^/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: delete, role: ROLE_ADMINISTRADOR }
        - { path: ^/planeacion/admin/, role: [ROLE_GESTIONAR_CONFIGURACION] }
        - { path: ^/planeacion/gestionar, role: [ROLE_GESTIONAR_PROFESOR] }
        - { path: ^/security/user/changePass, role: [ROLE_GESTIONAR_PROFESOR] }
        - { path: ^/security, role: [ROLE_ADMINISTRADOR]}
        - { path: ^/dashboard, role: IS_AUTHENTICATED_FULLY }

