adepsoft_menu_homepage:
    pattern:  /menu/config
    defaults: { _controller: ADEPSOFTMenuBundle:Default:index }
adepsoft_menu_config:
    pattern:  /menu/configAjax
    defaults: { _controller: ADEPSOFTMenuBundle:Default:config }

adepsoft_menu_move_node:
    pattern:  /menu/move_node
    defaults: { _controller: ADEPSOFTMenuBundle:Default:moveNode }

adepsoft_menu_delete_node:
    pattern:  /menu/delete_node
    defaults: { _controller: ADEPSOFTMenuBundle:Default:deleteNode }

adepsoft_menu_get_node:
    pattern:  /menu/get_node
    defaults: { _controller: ADEPSOFTMenuBundle:Default:getNode}

adepsoft_menu_copy_node:
    pattern:  /menu/copy_node
    defaults: { _controller: ADEPSOFTMenuBundle:Default:copyNode}

adepsoft_menu_create_node:
    pattern:  /menu/create_node
    defaults: { _controller: ADEPSOFTMenuBundle:Default:createNode}