parameters:
#    general_config.example.class: TotalPlanning\GeneralConfigBundle\Example

services:
#    general_config.example:
#        class: %general_config.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
