parameters:
#    Core_menu.example.class: Core\MenuBundle\Example

services:
#    Core_menu.example:
#        class: %Core_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    corssssse.twig.menu:
        class: Core\MenuBundle\Twig\MenuExtension
        tags:
            - { name: twig.extension }